### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "alborghetti123@gmail.com",
    "password":"123456789"
}


### Find a particular user with a ID
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth


### Delete a user given id
DELETE http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password":"AHA"
}